name: Parser Test

on:
  push:
    branches:
      - main
    paths:
      - TR.BBCodeLabel.Parser/**
      - TR.BBCodeLabel.Parser.Tests/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TEST_PROJECT_PATH: "TR.BBCodeLabel.Parser.Tests/TR.BBCodeLabel.Parser.Tests.csproj"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}
      - name: Build
        run: dotnet build --no-restore --configuration Release ${{ env.TEST_PROJECT_PATH }}
      - name: Test
        run: >
          dotnet test
          --no-build
          --verbosity normal
          --configuration Release
          --collect:"XPlat Code Coverage"
          --results-directory ./coverage
          ${{ env.TEST_PROJECT_PATH }}
      - name: Code Coverage Report
        # v1.3.0
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "0 80"
      - name: Show Code Coverage
        run: cat code-coverage-results.md > "$GITHUB_STEP_SUMMARY"
